# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer
  
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

#       - name: ruby versions
#         run: |
#           ruby --version
#           gem --version
#           bundler --version

#       # https://github.com/ruby/setup-ruby
#       - name: ruby setup
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.0.4
#           bundler-cache: true

      - name: Set Default Scheme
        run: default="sandbox-gh-actions"

      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p

      - name: Check Sims
        run: xcrun simctl list &>/dev/null

      - name: Run Tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -project sandbox-gh-actions.xcodeproj \
            -scheme sandbox-gh-actions \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'

      - name: Danger
        uses: danger/swift@3.3.0
        with:
            args: --failOnErrors --no-publish-check
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
