# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]
  
jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: default="sandbox-gh-actions"

      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p
        
      - name: Install Danger
        run: brew install danger/tap/danger-js

      - name: Run Tests
        run: |
          set -o pipefail
          xcodebuild clean test \
            -project sandbox-gh-actions.xcodeproj \
            -scheme sandbox-gh-actions \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'

      - name: Danger
        run: swift run danger-swift ci --verbose --failOnErrors
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
