name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Default Scheme
      run: default="sandbox-gh-actions"
    
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
      
    - name: Run Tests
      run: |
        set -o pipefail
        xcodebuild clean build \
          -project sandbox-gh-actions.xcodeproj \
          -scheme sandbox-gh-actions \
          -destination 'platform=iOS Simulator,name=Iphone 13,OS=15.4'
